Update requirements check

diff --git a/cms-manager b/cms-manager
--- a/cms-manager
+++ b/cms-manager
@@ -34,17 +34,17 @@ command -v apg >/dev/null 2>&1 || {
 }
 
 command -v mysql >/dev/null 2>&1 || {
-  echo >&2 "$(basename $0) requires apg but it's either not installed or not in PATH.  Aborting."
+  echo >&2 "$(basename $0) requires mysql but it's either not installed or not in PATH.  Aborting."
   exit 1
 }
 
 command -v mysqldump >/dev/null 2>&1 || {
-  echo >&2 "$(basename $0) requires apg but it's either not installed or not in PATH.  Aborting."
+  echo >&2 "$(basename $0) requires mysqldump but it's either not installed or not in PATH.  Aborting."
   exit 1
 }
 
 command -v mysqlshow >/dev/null 2>&1 || {
-  echo >&2 "$(basename $0) requires apg but it's either not installed or not in PATH.  Aborting."
+  echo >&2 "$(basename $0) requires mysqlshow but it's either not installed or not in PATH.  Aborting."
   exit 1
 }
 
